project:
  type: website

website:
  title: Seeing the Unseen
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-Exercises/project-final-Data-Diggers
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
      - text: Age Dashboard
        href: agedashboard.qmd

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto
